version: '2'
services:
  sce-printer:
    container_name: sce-printer
    build:
      context: .
      dockerfile: ./printer/Dockerfile
    privileged: true
    restart: "no"
    volumes:
      - ~/.ssh/id_ed25519.pub:/app/ssh_key.pub
      - ~/.ssh/id_ed25519:/app/ssh_key
      - ~/.ssh/known_hosts:/app/known_hosts
      - "/etc/cups/ppd/:/etc/cups/ppd"
    tty: true
