version: '2'
services:
  sce-ledsign:
    container_name: sce-ledsign
    build:
      context: .
      dockerfile: ./ledsign/Dockerfile
    networks:
      - quasar-local
  sce-printer:
    container_name: sce-printer
    build:
      context: .
      dockerfile: ./printer/Dockerfile
    privileged: true
    environment:
      - LEFT_PRINTER_NAME=${LEFT_PRINTER_NAME}
      - RIGHT_PRINTER_NAME=${RIGHT_PRINTER_NAME}
      - LEFT_PRINTER_IP=${LEFT_PRINTER_IP}
      - RIGHT_PRINTER_IP=${RIGHT_PRINTER_IP}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - "/etc/cups/ppd/:/etc/cups/ppd"
    networks:
      - quasar-local
  conn:
    build:
      context: .
      dockerfile: ./tunnel/Dockerfile
    volumes:
      - ~/.ssh/id_rsa.pub:/app/test_keys.pub
      - ~/.ssh/id_rsa:/app/test_keys
      - ~/.ssh/known_hosts:/app/known_hosts
    tty: true
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    devices:
      - /dev/kmsg:/dev/kmsg
    depends_on:
      - sce-ledsign
      - sce-printer
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'  
networks:
  quasar-local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24
          gateway: 172.100.0.254
