version: '2'
services:
  sce-ledsign:
    container_name: sce-ledsign
    build:
      context: .
      dockerfile: ./ledsign/Dockerfile
    networks:
      - quasar-local
  sce-printer:
    container_name: sce-printer
    build:
      context: .
      dockerfile: ./printer/Dockerfile
    privileged: true
    environment:
      - LEFT_PRINTER_NAME=${LEFT_PRINTER_NAME}
      - RIGHT_PRINTER_NAME=${RIGHT_PRINTER_NAME}
      - LEFT_PRINTER_IP=${LEFT_PRINTER_IP}
      - RIGHT_PRINTER_IP=${RIGHT_PRINTER_IP}
      # - CUPS_LPADMIN_PRINTER1="lpadmin -p ${LEFT_PRINTER_NAME} -v ${LEFT_PRINTER_IP}"
      # - CUPS_LPADMIN_PRINTER1_ENABLE="cupsenable ${LEFT_PRINTER_NAME}"
      # - CUPS_LPADMIN_PRINTER1_ACCEPT="cupsaccept ${LEFT_PRINTER_NAME}"
      # - CUPS_LPADMIN_PRINTER2="lpadmin -p ${RIGHT_PRINTER_NAME} -v ${RIGHT_PRINTER_IP}"
      # - CUPS_LPADMIN_PRINTER2_ENABLE="cupsenable ${RIGHT_PRINTER_NAME}"
      # - CUPS_LPADMIN_PRINTER2_ACCEPT="cupsaccept ${RIGHT_PRINTER_NAME}"
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - "/etc/cups/ppd/:/etc/cups/ppd"
    networks:
      - quasar-local

networks:
  quasar-local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24
          gateway: 172.100.0.254
