version: '2'
services:
  sce-printer:
    container_name: sce-printer
    build:
      context: .
      dockerfile: ./printer/Dockerfile.dev
    privileged: true
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./config:/app/config
      - ./printer:/app/printer
      - ./util:/app/util
