version: '2'
services:
  sce-printer:
    container_name: sce-printer
    build:
      context: .
      dockerfile: ./printer/Dockerfile.dev
    ports:
      - 9000:9000
    volumes:
      - ./config:/app/config
      - ./printer:/app/printer
