{
 "title": "Updated Dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Right Printer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "laserJet",
     "select": [
      [
       { "params": [ "pagesPrinted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "Left" }
     ]
    },
    {
     "alias": "Left Printer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "laserJet",
     "select": [
      [
       { "params": [ "pagesPrinted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "Right" }
     ]
    }
   ]
  },
  {
   "title": "Ink Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Right Printer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "laserJet",
     "select": [
      [
       { "params": [ "inkLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "Left" }
     ]
    },
    {
     "alias": "Left Printer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "laserJet",
     "select": [
      [
       { "params": [ "inkLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "Right" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Right Printer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "laserJet",
     "select": [
      [
       { "params": [ "memoryUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "Left" }
     ]
    },
    {
     "alias": "Left Printer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "laserJet",
     "select": [
      [
       { "params": [ "memoryUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "Right" }
     ]
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time_spent_querying_data_Left{app=\"printer-temp\"}",
     "legendFormat": "Left Latency "
    },
    {
     "expr": "time_spent_querying_data_Right{app=\"printer-temp\"}",
     "legendFormat": "Right Latency "
    }
   ]
  },
  {
   "title": "Current Toner Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Right Printer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "laserJet",
     "select": [
      [
       { "params": [ "currentTonerLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "Left" }
     ]
    },
    {
     "alias": "Left Printer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "laserJet",
     "select": [
      [
       { "params": [ "currentTonerLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "Right" }
     ]
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app=\"printer-temp\"}"
    }
   ]
  },
  {
   "title": "Last Seen",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - (Right_last_seen{app=\"printer-temp\"} / 1000)",
     "legendFormat": "Left Last Seen"
    },
    {
     "expr": "time() - (Left_last_seen{app=\"printer-temp\"} / 1000)",
     "legendFormat": "Right Last Seen"
    }
   ]
  }
 ]
}