global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'sce-printer'
    static_configs:
      - targets: ['sce-printer:5000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
