{
 "title": "printer snmp",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "# of pages printed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "page_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "snmp request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "snmp_request_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ink level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "ink_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}