groups: 
  - name: alert_rules
    interval: 15s
    rules: 
      - alert: container_not_running
        expr: |
          time() - container_last_seen{name="quasar_grafana"} > 60
            or
          time() - container_last_seen{name="quasar_nginx"} > 60
            or
          time() - container_last_seen{name="sce-ledsign"} > 60
            or
          time() - container_last_seen{name="sce-printer"} > 60
            or
          time() - container_last_seen{name="quasar_influx"} > 60
            or
          time() - container_last_seen{name="quasar_cadvisor"} > 60
            or
          time() - container_last_seen{name="quasar_grafana"} > 60
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Container "{{ $labels.name }}" is not running
          description: 'container "{{ $labels.name }}" has been down for more than {{ $value | printf "%.0f" }}'
      - alert: Error_idk_temporary
        expr: |
          increase(errorAmount[1m]) > 0
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: Its doing false
          description: Hella false
