FROM node:14.10.0-alpine

WORKDIR /app

RUN apk add jq

COPY ./package.json .

COPY ./package-lock.json .

RUN npm install

RUN npm i -g nodemon

COPY ./config/config.json /app/config/config.json

COPY ./printer /app/printer

COPY ./util /app/util

ENV NODE_ENV="dev"

ENTRYPOINT [ "./printer/run_dev_container.sh" ]
